# Generated by Django 4.2 on 2023-05-03 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import freeboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FreePost",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField()),
                ("modify_date", models.DateTimeField(blank=True, null=True)),
                ("click", models.IntegerField(default=0, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_author_question",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "freepost",
            },
        ),
        migrations.CreateModel(
            name="FreePostImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "freeimage",
                    models.ImageField(upload_to=freeboard.models.image_upload_path),
                ),
                (
                    "freepost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freeimage",
                        to="freeboard.freepost",
                    ),
                ),
            ],
            options={
                "db_table": "free_post_image",
            },
        ),
        migrations.CreateModel(
            name="FreeComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField()),
                ("modify_date", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_author_answer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "freepost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="freeboard.freepost",
                    ),
                ),
            ],
        ),
    ]
