# Generated by Django 4.2 on 2023-05-11 10:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freeboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freepost",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
