# Generated by Django 4.2 on 2023-05-03 10:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0003_alter_post_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Answer",
            new_name="Comment",
        ),
    ]
